
package billingService.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Bill", targetNamespace = "http://ws.billingService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Bill {


    /**
     * 
     * @param billData
     * @return
     *     returns billingService.ws.Status
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "process", targetNamespace = "http://ws.billingService/", className = "billingService.ws.Process")
    @ResponseWrapper(localName = "processResponse", targetNamespace = "http://ws.billingService/", className = "billingService.ws.ProcessResponse")
    public Status process(
        @WebParam(name = "Bill", targetNamespace = "")
        Bill_Type billData);

}
